BINCONTAINER := "pellepedro/binpot:nvim"
export BUILDX_PLATFORMS := "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"

docker-build:
  docker buildx build --no-cache --output type=docker,name={{ BINCONTAINER }} - < Dockerfile.alpine
  # docker buildx build --no-cache -f Dockerfile.alpine --tag {{ BINCONTAINER }} --push .

run:
  docker run -it {{ BINCONTAINER }}

docker-push: docker-build
  docker push {{BINCONTAINER}}
